entryPoints:
  web:
    address: ":9090"
  websecure:
    address: ":9443"

providers:
  consulCatalog:
    defaultRule: "Host(`{{ .Name }}.localhost`)"
    exposedByDefault: true
    endpoint:
      address: 127.0.0.1:8500
      scheme: http

api:
  insecure: true
  dashboard: true
